version: '3.9'
services:
 xtr3:
    container_name: xtr3
    build:
      context: .
    ports:
      - 9020:8080
    volumes:
      - ./DSL:/DSL
    networks:
      - bykstack

networks:
  bykstack:
    name: bykstack
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
